### ISSUE TITLE
bamboo-cxx fails on the 7 point example

### ISSUE THREAD

**Issue by scottb5612** [SergioMartin86/bamboo6#10]
I can generate code using bamboo-translate,
but the generated code cannot compile without unrecoverable errors (on sorken)
I verified this on stampede as well.

**Comment by SergioMartin86** [comment]
This is working just fine for me. Have you tried with the latest revision?

If this is still failing, re-open the issue and provide more details (such as which build command you are using)

**Comment by scottb5612** [comment]
Still cannot get it to compile
Here are some of the errors.
Please share your input source with me so we know we are working with the same code.
Scott

bamboo_7_point_stencil.cpp:627:74: error: invalid conversion from ‘int’ to ‘const void*’ [-fpermissive]
In file included from /state/partition1/apps/gcc-4.7.1/lib/gcc/x86_64-redhat-linux/4.7.1/../../../../include/c++/4.7.1/cstring:44:0,
                 from /home/baden/bin/bamboo_v6.0/tarragon/include/task.h:24,

/usr/include/string.h:44:14: error:   initializing argument 2 of ‘void* memcpy(void*, const void*, size_t)’ [-fpermissive]
bamboo_7_point_stencil.cpp: In member function ‘virtual void _BAMBOODummyClass::vinject(tgn::Message*)’:
bamboo_7_point_stencil.cpp:910:20: error: label ‘_tarragonInjectLoop1’ used but not defined

**Comment by SergioMartin86** [comment]
This is working for me now.

Be sure you are using 
> make
> ./run_test.sh

To try any of the examples in the examples dir.

**Comment by scottb5612** [comment]
It works now.
There was a mistake in how I was invoking the program from the command line.
I noticed this comment in the log

This is a special statement (not associated with the original source code, comment relocation is not supported for these statements) targetStmt file id = -3

What is it about?

Scott
