### ISSUE TITLE
Integrate Bamboo Checker

### ISSUE THREAD

**Issue by SergioMartin86** [SergioMartin86/bamboo6#12]
Bamboo itself has an unreliable/silent syntax verification system. I have to implement bamboo checker into into its code to do a formal verification before letting bamboo modify the code.

**Comment by SergioMartin86** [comment]
Done

**Comment by scottb5612** [comment]
I created a simple annotatoin syntax error by miss-spelling the
"dimension" keyword as "diminsion"

I got this error, which isn't intuitive.
[Bamboo] Pre-Processor: Performing Code Verifications
[Bamboo] Line 14: [Error] Missing required basic block {...} or for(){...} statement after pragma.

We can put this issue on hold for now.
Scott

**Comment by SergioMartin86** [comment]
This was an easy fix, you can re-try now.

**Comment by scottb5612** [comment]
This is better, but there are really 2 errors
A misspelled pragma
And the error reported below because a valid pragmas was missing.
[Bamboo] Line 13: [Error] Bamboo pragma missing [send|receive|compute|olap|dimension] option.
By default, bamboo used to define dimension as 1.
has this changed?

**Comment by SergioMartin86** [comment]
Well using strict logic, "missing [send|receive|compute|olap|dimension] option" in itself includes a misspelled pragma. More specific would be "unrecognized pragma option". However, this is a little tricky to implement. I would settle with the general error message for now.

I didn't change any defaults as far as I am concerned. On the other hand, my opinion is that the dimension value is just an argument to tarragon. It can be deduced from which -tarragonP# you use without the use of any pragma. But this is something to think about when we have a stable version of Bamboo.

**Comment by scottb5612** [comment]
Let's return to this later on when we really get into error reporting.

By default, bamboo used to define dimension as 1.
Has this changed?

**Comment by SergioMartin86** [comment]
No, it didn't change as far as I am concerned.

**Comment by scottb5612** [comment]
I agree that it's hard to detect misspelled pragmas.
But the above error was only the result of misspelling the dimension pragma, which is set to 1 by default anyway. There were no missing blocks as there was a colllective.
So technically there are no missing pragmas.
 Only a bamboo pragma that cannot be recognized.
See my point?
Or, have you changed things with the Bamboo collectives so that the collective doesn't need to get inlined up to main?  They were with Bamboo 5.4 so there was a defined olap region with send and recv block..

**Comment by scottb5612** [comment]
That's  a run time issue. Don't you need to know the # of dimensions at compile time to handle, say,
nearest neighbor connections?
What else is dimension really used for ?

"my opinion is that the dimension value is just an argument to tarragon. It can be deduced from which -tarragonP# you use without the use of any pragma. But this is something to think about when we have a stable version of Bamboo."

**Comment by SergioMartin86** [comment]
I'm closing this issue because the pre-processor has been successfully integrated.
I'm opening a new issue with the questions you have just asked.
You can open a new enhancement/bug issue detailing if/how it should behave differently.
