### ISSUE TITLE
Remove const dataypes in translated code

### ISSUE THREAD

**Issue by SergioMartin86** [SergioMartin86/bamboo6#14]
Const datatypes are not necessary in a translated code and introduce errors. Solution is to remove all generated const datatypes.

**Comment by scottb5612** [comment]
Can you say a bit more about this? I'm not clear on what you mean.

**Comment by SergioMartin86** [comment]
This was a bug in ROSE/Bamboo where normal variables were moved from main to the olap class, but with an added "const" modifier.

This, and a lot of error messages, seem to arise from the usage of deepcopy. I'll investigate further about this with the ROSE team.
