### ISSUE TITLE
error messages about inlining

### ISSUE THREAD

**Issue by scottb5612** [SergioMartin86/bamboo6#16]
I see 2 kinds of messages related to inlining
One make sense, where you report each function you've inlined 
But the other, repeatedly mentions the same one.
not sure why

[Bamboo] inlining the function fill_partition_f2c, which holds MPI_Comm_rank
[Bamboo] inlining the function fill_partition_f2c, which holds MPI_Comm_size
[Bamboo] inlining the function fill_partition_f2c, which holds MPI_Send
[Bamboo] inlining the function fill_partition_f2c, which holds MPI_Recv
[Bamboo] inlining the function fill_partition_f2c, which holds MPI_Send
[many more lines]

**Comment by SergioMartin86** [comment]
These are not error messages, just information about what's going on.
However, it makes sense to clarify as the message is incorrect. There's no 5 inlinings, just 5 functions found that trigger the one inline. I'll fix this later.

**Comment by SergioMartin86** [comment]
Ok, I've made the corresponding changes to the inlining logs. Also embellished and clarified the log messages in general.
Let me know if this is clearer!
