### ISSUE TITLE
Remove Opaque var references from rankAndSize.C

### ISSUE THREAD

**Issue by SergioMartin86** [SergioMartin86/bamboo6#18]
Opaque var references were effectively removed from all other source files, but it creates problems in rankAndSize.C. I have to check why this is and solve it.

**Comment by SergioMartin86** [comment]
There's no good way to do this without compromising Bamboo's integrity

**Comment by scottb5612** [comment]
Can you explain the issues here?



—

**Comment by SergioMartin86** [comment]
In ROSE, a variable definition is, for example, when you have the following instruction:
a++;

In this case, you have an increment expression node (++) containing a variable reference expression (a). 

There is two ways to create a variable reference expression in ROSE. The first one is to use buildVarRefExp(string variable_name). This function requires that the symbol specified is defined in the scope's symbol table. It is ideal to use this one because it provides a verification that you are not referencing non-declared variables. 

The other one is to use an opaque variable reference using buildOpaqueVarRefExp(string variable_name). This function does not check if the symbol is not defined in the symbol table, and proceeds to create the reference anyway. This is useful, for example, in some cases you create the reference before the declaration of the variable itself.

Using opaque references to variables without care can be problematic. First of all, every use instance generates a warning in the log file, even if the variable symbol is found in the symbol table. Second, since it doesn't enforce to check for existing declarations, it could lead to broken code where there are references to non-existing variables (you have witnessed this several times).

I tried converting all opaque variable reference to their normal counterparts, reducing the log size and hoping that ROSE would fail (so I can trace and fix any problem in particular) for each non-declared variable reference. However, and I think this is a ROSE bug, in normal variable references, when the symbol is not found, ROSE would not fail. Instead it takes any other existing symbol, in hopes to save the translation. This is very very bad, because translation would be fine, but then in compilation time you find out that there are strange references like malloc(argv) !!

So I had to take my modifications back and let the opaque references be for the time being.

But this is not the worst. buildOpaqueVarRefExp allows you to cheat ROSE. Abusing the fact that ROSE doesn't check them, you can disguise complex language construction as opaque variable references and insert them as plain text in your code. For example, take bamboo.C, line 420:

SgVarRefExp* gotoExitVarRef= buildOpaqueVarRefExp("goto _tarragonExecuteExit");

In this case, the structure being created is NOT a variable reference, but a complex structure (one requiring a node sub-tree). The correct way to do it is to use the corresponding buildGotoStatement function. Although this may save development effort, it breaks the consistency of the AST, as complex structures are being disguised as variable references. I am sure that many of the bugs and warning 
messages are generated from this. Unfortunately, Bamboo is plagued with this kind of shortcuts.

Things like this, but especially this one, tells me that Bamboo is not a recoverable piece of code. Solving this from root would take a lot of effort, and I'm not sure its worth it.
