### ISSUE TITLE
Allow arbitrary order in arguments to bamboo-translate

### ISSUE THREAD

**Issue by scottb5612** [SergioMartin86/bamboo6#19]
Every time I rebuild bamboo, I have to edit bamboo-cxx and bamboo-translate
with custom include paths.. Hope this is coming soon, would save time and errors.

**Comment by SergioMartin86** [comment]
I've just added this feature, try and let me know if it worked!

**Comment by scottb5612** [comment]
I am able to use -I for bamboo-cxx, as well as -fpemissive
But I am not able to use the -I option for bamboo-translate, 

bamboo-translate -I./include -I../cart3d/include -I../include `xml2-config --cflags` superMain.c 
[Bamboo] Fatal error: input file is not specified or not found.

**Comment by SergioMartin86** [comment]
Oh, I forgot to mention: the filename has to be the first argument. Like this:

bamboo-translate superMain.c  -I./include -I../cart3d/include -I../include xml2-config --cflags

**Comment by scottb5612** [comment]
Hmm. Is there any way to make the two utilties treat the file name consistently?
It will confuse users.
Scott

**Comment by SergioMartin86** [comment]
I know... I agree with that. Nonetheless, it is a little tricky to do that. I'll see what I can do...

**Comment by scottb5612** [comment]
That's OK. Let's leave this on your todo list.
we have bigger fish to fry!
Scott

**Comment by SergioMartin86** [comment]
I think we can be more ambitious with this and allow multi-file input to bamboo-translate. This way you don't need to coalesce all .c's into superMain.c.

This would be a big one, but I think it's plausible.

**Comment by scottb5612** [comment]
This would be great. One thing I had to be careful of when concatenating multiple files
was interactions involving #defines. Luckily the cart3d code (usually) took the convention that
anything #defined in a file had to #undefined at the end. But one must be aware
of the possible problems that static definitions local to a single file.

Scott

**Comment by SergioMartin86** [comment]
Believe it or not this is ready to be tested:

- You can throw whatever you want at bamboo-translate, including codefiles, compilation flags, and -I/lib_path flags. All mixed up in any order.
- Bamboo will detect which file contains the main function and name the bamboo_ file based on it. This makes this new approach backward-compatible. 
- Curiously, making this change allowed me to simplify a handful of things in Bamboo. E.g.: the bamboo-translate script is much more lightweight since it doesn't have to figure out which files are being produced.

I've changed the 7_point_stencil example to be multi-file, if you want to try it and see for yourself. We'll have to do the same with the mpix example, as I would like to abandon the superMain.cpp approach.

**Comment by scottb5612** [comment]
I tried the new translator, and the generated code was much shorter than before, about a factor of 2.
This is good, because there is one knob I have to turn: unroll multigrid by a factor of 4, rather than a factor of 1. I have avoided this because of the code sizes (200K lines) and compile times (45 minutes)

Unfortunately, the code wouldn't compile. 
Here is the output:

bamboo_main.cpp:765:1: error: unterminated #else
bamboo_main.cpp: In member function ‘virtual void _BAMBOODummyClass::vexecute()’:
bamboo_main.cpp:8034: error: ‘limitGradients’ was not declared in this scope


Here is the bamboo-translate invocation, note the -D options. I'm assuming they work with bamboo-translate, but wasn't sure. (They are used in generating superMain.c)

 bamboo-translate main.c mpi_par.c mpi_par_types.c mpi_par_bcast.c mpi_par_snd_rcv.c mpi_par_exchange.c mpi_exchange_promgstuf.c mpi_exchangeGradient.c mpi_exchange_resmgstuff.c genRecvLists.c mesh_io_fill_partitionsSFC.c setup.c mesh_io_mpi.c limiters.c do_mg_cycle.c mg_stuff.c runge_kutta.c convergence.c -DLINUX64 -DNO_ALLOCA -DSTICKLER -DUNROLL_MG=1 -D_BAMBOO_ -I./include -I/home/sbaden/cart3d/include -I/home/sbaden/include -I/usr/include/libxml2 

**Here is the bamboo-cxx invocation**

bamboo-cxx -c -DLINUX64 -DNO_ALLOCA -DSTICKLER -DUNROLL_MG=1 -D_BAMBOO_ -I./include -I/home/sbaden/cart3d/include -I/home/sbaden/include -I/usr/include/libxml2  bamboo_main.cpp


I can see a problem here: I need to use the intel compiler for building the binary of bamboo_main
I use that compiler to build the rest of the app (recall that I haven't successfully ported cart3d to gnu-land, and I don't know if that will ever happen at least I don't have the time)

On another note, I was able to build   using superMain.c I'm opening a new discussion on that.

I noticed that there was no bamboo log file.  That's ok with me but there probably needs to be a way of turning on various levels of verbosity (we can hold off on that)

Some other random facts. I was able to build the 7 point solver on sorken but not at NYU.
bamboo-translate fails.
 The problem is that /usr/include is hard coded into the Makefile.

sbaden@juniper[include]$ bamboo-translate -I/usr/include getTime.cpp 7_point_stencil.cpp residual.cpp
[Bamboo] Beginning translation...
[Bamboo] Building AST of the input source...
Catastrophic error: cannot open source file "/usr/include/getTime.cpp"

**Comment by scottb5612** [comment]
The new translator failed on Stampede

bamboo-translate main.c mpi_par.c mpi_par_types.c mpi_par_bcast.c mpi_par_snd_rcv.c mpi_par_exchange.c mpi_exchange_promgstuf.c mpi_exchangeGradient.c mpi_exchange_resmgstuff.c genRecvLists.c mesh_io_fill_partitionsSFC.c setup.c mesh_io_mpi.c limiters.c do_mg_cycle.c mg_stuff.c runge_kutta.c convergence.c -DLINUX64 -DNO_ALLOCA -DSTICKLER -DUNROLL_MG=1 -D_BAMBOO_ -I./include -I../cart3d/include -I../include -I/usr/include/libxml2

[Bamboo] Inserting header files...
[Bamboo] Creating BambooTask class member functions and variables...
[Bamboo] Creating BambooTask class declarations and variables...
[Bamboo] Outlining source code...
[Bamboo] Finding and translating MPI calls...
[Bamboo] Overlap regions found: 55.
[Bamboo] Exploring the iteration space...
[Bamboo] Building Tarragon graph configuration...
[Bamboo] Post-Processor: Detecting MPI containing functions...
[Bamboo] Post-Processor: Removing MPI containing function definitions...
[Bamboo] Post-Processor: Removing MPI containing function declarations...
/home1/00660/tg458182/bin/bamboo_v6.0/bamboo-translate: line 6: 47823 Segmentation fault      (core dumped) $command > /dev/null

**Comment by scottb5612** [comment]
The failure mode was exactly the same on Sorken.

**Comment by scottb5612** [comment]
For some reason, only the NYU machine will use the new version of bamboo-translate.
Not sure why, though I cannot compile the 7-point app after translating.
Must be something about the environment.
I'm using gcc-4.7, Oh boy. I may have changed the compiler at some point, after building my initial version of bamboo6. 

Should I scrape and clean everything and rebuild bamboo ?
I would use gcc-4.7.2, which I see commented outing my .bashrc

Scott

**Comment by scottb5612** [comment]
I am reopening this thread

**Comment by SergioMartin86** [comment]
Probably the best thing for you to do is:

- Choose your favorite gcc, and configure your .bashrc to always use it.
- Scrape everything bamboo/rose/tarragon related.
- Checkout bamboo and recompile everything again.
- Try again :sweat_smile:

**Comment by scottb5612** [comment]
Yup, that's what I did. Funny thing is nothing changed!
Scott

**Comment by SergioMartin86** [comment]
I've been able to check this. I almost faint when I saw bamboo failing with our stable 7_point_stencil... "Luckly", this seems to be a bug introduced by compiling ROSE with the intel compiler.

I hypothesize that the solution is to recompile ROSE/Bamboo with gcc. I'll check this approach tomorrow.

**Comment by scottb5612** [comment]
That's odd, because I rebuilt everything from scratch.
Look in my config.log at NYU at sbaden/Downloads/build-dir/rose_build/config.log

**Comment by SergioMartin86** [comment]
Ok, I've found the root of all evil. Seems that ROSE/EDG/Bamboo use gcc/icc during execution, and it needs to be the exact same version when you translate as the one you used to build bamboo. 
It took me a while to figure this out because I too got entangled with all the compiler options, and because I use two consoles and I kept forgetting to make sure both have the same configured compiler.

Now I'd like to check if the Intel compiler works on its own.

**Comment by SergioMartin86** [comment]
Ok, no... this is not or fault. This seems to be a bug in the latest release of ROSE. I'll try with the other ROSE repo with the latest stable release.
I'll let the guys here know too.

**Comment by SergioMartin86** [comment]
Oh gee, what a relief. I've just confirmed that with a previous revision of ROSE, Bamboo works correctly.
I am committing a new bamboo revision that uses this specific revision so the problem is solved forever.
In the meantime, I'll report this to the ROSE guys.

Also, it seems that the compiler you use doesn't have anything to do with this problem.


Let me know if it works for you now.

**Comment by scottb5612** [comment]
Ok, will do.
Do I need to scrape everything clean including prior installations of rose and boost?

**Comment by SergioMartin86** [comment]
Yes, you need to rebuild everything. Now, it's importantt that you follow these steps in Stampede:
1) Since you'll want to use the intel/15.0.2 compiler to build and link cart3d, you'll need to build Bamboo using with gcc/4.4.6 (the Intel compiler won't work for building ROSE). 
2) Switch to intel/15.0.2, and recompile Bamboo only using "make clean install"
3) Now you can translate and compile/link Cart3D
Let me know if you get stuck in any of these steps. In the meantime, this issue is finally closable.

**Comment by scottb5612** [comment]
So

1.I load gcc/4.46  configure bamboo and then do "make"
2. When step (1) is done I switch to the intel compiler and  then build bamboo again
"Make clean install

So what I think is happening is that I need to make sure that I build rose with the gnu compiler.
Bamboo itself is not so restricted.

**Comment by SergioMartin86** [comment]
Exactly. Also, I think you may need to run configure.sh again after installing ROSE, but let me know how that goes.

**Comment by scottb5612** [comment]
By the way, why gcc 4.4.6?
I have 4.4.7 at NYU I assume that's OK.
Also, is intel 15.0 necessary? I've not built cart3d with any intel compiler beyond v14.0
Proabbly OK but beware.
Scott

**Comment by scottb5612** [comment]
Drat... sourceforge is timing out when trying to download boost.
Will have to  try later on.

**Comment by SergioMartin86** [comment]
I would say don't worry... Bamboo is in good shape now. Let me struggle with cart3D this week and we'll catch up when you are back.

**Comment by scottb5612** [comment]
That is a good idea, as a  I'm not sure how to switch the Bamboo build to the intel compiler
gcc 4.4.7 is available by default.
mpicc uses it, even if I load the intel compiler.
