### ISSUE TITLE
unpruned routines

### ISSUE THREAD

**Issue by scottb5612** [SergioMartin86/bamboo6#20]
For some reason, not all routines that get inlined are being pruned. Not sure why,this is a holdover
from v5.4. We'll go over this when I hand off the code. Putting this issue here, so I don't forget.

**Comment by SergioMartin86** [comment]
Can you explain to me what pruning is?... I'm guessing removing the local variables and inserting them into the global class scope?

**Comment by scottb5612** [comment]
When Bamboo inlines a function, it also generates a translated version of that function.
But such functions are of no use and for some reason they won't compile correctly.
Tan realized the issue and wrote an AST pruner that removed such functions,
but for some reason it didn't remove all of them, and of those it didn't remove, 2 rather large
ones interfered with compilation. I removed these manually after translation, but it would be nice to 
fix this. I can't see why these particular routines should be included, since they appear int the same file along with other routines that get pruned.
  It' time for us to have you get your hands wet with Cart3d!

Scott

**Comment by SergioMartin86** [comment]
This should be solved now

**Comment by scottb5612** [comment]
It is
