### ISSUE TITLE
Problem with enumerated types (in with typedefs, too)

### ISSUE THREAD

**Issue by scottb5612** [SergioMartin86/bamboo6#21]
I will upload a test called redty3 which
uses an enumerated type.

Bamboo raises and unrecoverable err (I've show you some other conversion issues which I avoided with -fpermissive)
bamboo_redty3.cpp:51:8: error: use of enum ‘__anonymous_0x4252220’ without previous declaration
bamboo_redty3.cpp: In member function ‘virtual void _BAMBOODummyClass::vexecute()’:
bamboo_redty3.cpp:240:8: warning: invalid conversion from ‘int’ to ‘etype’ [-fpermissive]
bamboo_redty3.cpp:10:6: warning:   initializing argument 1 of ‘void F(etype)’ [-fpermissive]

**Comment by scottb5612** [comment]
The code is here:
https://www.dropbox.com/sh/lzia6ta5bqerlpw/AAACuXdNoDKc8Tkj40E8Pz6Pa?dl=0

**Comment by SergioMartin86** [comment]
I've added the example to the repository. I've tested and reproduced the error.

I'm sure you are aware that, if you put the enum declaration in the .c file it works fine, right?

**Comment by SergioMartin86** [comment]
I don't really see a clean solution for this. I think there are things more prioritary to solve, e.g. struct types. 

In the meantime we can deal with it by including the enum in the .c file.

**Comment by scottb5612** [comment]
Yes, it does work when I include the enum file.
But cart3d is too big to be expanding all these things.
It calls libraries that I am hoping not to mess with.
But let's discuss this in a skype call soon.

 Even when I turn the example  into  a .cpp file, it fails.
Here is the example code, look in directory redty4
It's the c++ version of redty3 which I gave you yesterday

https://www.dropbox.com/sh/8jg47ak7bb703i9/AACY54QIJ2aJ-900sJO1OhYta?dl=0


I think this is a special case of a more general issue involving typedefs and I am running into another problem. But I feel we arg getting close again!
Scott

**Comment by SergioMartin86** [comment]
ooook, this was a tough nut to crack but I think I solved it. Wanna check again and close the issue if it's solved?

**Comment by scottb5612** [comment]
The enumerated types seem to work, but the sum doesn't print out.
I ran the program like so, but both tasks have a rank of 1 so the message doesn't print out.
See test redty3.c
mpirun -np 1 ./a.out -tarragonP0 2 -w 2

I also tried with -np 2 as well, same result

**Comment by SergioMartin86** [comment]
The enums bug is solved. I'll add this as different bug.
