### ISSUE TITLE
redty example is not working properly.

### ISSUE THREAD

**Issue by SergioMartin86** [SergioMartin86/bamboo6#28]
I ran the program like so, but both tasks have a rank of 1 so the message doesn't print out.
See test redty3.c
mpirun -np 1 ./a.out -tarragonP0 2 -w 2

I also tried with -np 2 as well, same result

**Comment by SergioMartin86** [comment]
Ok, I found the error. It seems that calling MPI_Comm_Rank more than just once messes with Bamboo. sigh... I'll see if this is a quick fix.

**Comment by SergioMartin86** [comment]
Ok, it wasn't a quick fix, but it revealed a couple of ugly bugs that I'm glad to have discovered.
There was 1 bug in the Bamboo Reduce function where the send buffer (in this case, the rank variable!) was used as temporal buffer for intermediate results.

I also removed translation for MPI_Init, MPI_Finalize, MPI_Comm_Size, MPI_Comm_Rank by replacing them with Bamboo_ counterparts. This makes code cleaner, more transparent, and less bug-prone.

Also, I created a run_test.sh file for the redty3 example so you can execute it easily.

Last but not least, I added a bamboo postprocessor to convert all MPI_Calls to Bamboo calls. 

As always, reopen if fails.

**Comment by scottb5612** [comment]
Looks like Bamboo_Allgatherv is not defined.
Yes, there is only 1 warning message now.

bamboo_superMain.cpp: In function ‘tSR_Item* GenAdjMat(int*, tSR_Item*, gstore*)’:
bamboo_superMain.cpp:16738:144: error: ‘Bamboo_Allgatherv’ was not declared in this scope

**Comment by SergioMartin86** [comment]
Tan never programmed this collective, did he? I cannot find it in my version of Bamboo.

**Comment by scottb5612** [comment]
I had assumed he had, since it was in the cart3d code. But maybe not.
