### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by scottb5612** [SergioMartin86/bamboo6#33]
I get many many of the following errors

sbaden@juniper[mpix_flowCart]$ bcxx
bamboo_superMain.cpp:11471: error: reference to ‘i’ is ambiguous
bamboo_superMain.cpp:1395: error: candidates are: int OlapClass80::i
bamboo_superMain.cpp:1847: error:                 int OlapClass75::i
bamboo_superMain.cpp:2839: error:                 int OlapClass58::i
bamboo_superMain.cpp:3195: error:                 int OlapClass55::i
bamboo_superMain.cpp:3531: error:                 int OlapClass50::i
bamboo_superMain.cpp:3847: error:                 int OlapClass46::i
bamboo_superMain.cpp:4163: error:                 int OlapClass43::i
bamboo_superMain.cpp:4479: error:                 int OlapClass39::i
bamboo_superMain.cpp:4787: error:                 int OlapClass35::i
bamboo_superMain.cpp:5926: error:                 int OlapClass16::i
...

**Comment by SergioMartin86** [comment]
This should be solved now, wanna check again?

**Comment by SergioMartin86** [comment]
Actually no, it's not solved yet, I have to make an additional change.

**Comment by scottb5612** [comment]
That problem went away yesterday.

**Comment by SergioMartin86** [comment]
This is still happening.

**Comment by SergioMartin86** [comment]
Just solved it. It was a problem with the inliner:
If you define a variable inside a for statement (i.e. for(int i;;)), it gets globalized by bamboo but also survives in the local scope. Solution is to pre-declare the variable before the for statement. I did this for all the collective functions, and also gave them non-polluting names (e.g. mask -> __mask).

Works well now!
