### ISSUE TITLE
Remove mangled name references

### ISSUE THREAD

**Issue by SergioMartin86** [SergioMartin86/bamboo6#34]
None of them are probably necessary, and are bug-prone

**Comment by scottb5612** [comment]
What was the issue here?

**Comment by SergioMartin86** [comment]
In some points in Bamboo (not anymore in the code inliner since I changed it), some mangled names (ROSE internal names for AST Nodes) are used for mapping functions or variables to their definitions. This is quite dangerous because it relies in an internal information of ROSE, which might change in the future.

As far as I have seen, it's not really necessary to add mangled names to maps in Bamboo and I think it will probably best to fix that. But this is really low priority right now.

**Comment by scottb5612** [comment]
So there are other places where mangled names are used?
I agree this is dangerous

**Comment by SergioMartin86** [comment]
My bad, I thought there were more mangled name refs, but those in the inliner were the only ones.
