### ISSUE TITLE
Linking error with bamboo_superMain.cpp

### ISSUE THREAD

**Issue by scottb5612** [SergioMartin86/bamboo6#35]
I am getting some loader errors when I build Cart3d

bamboo_superMain.cpp:(.text+0x1cb0): undefined reference to `Bamboo_Allgatherv( ...)

as well as many errors involving stream I/O invokes by Bamboo internals.
The complete log is here (wish I could attach a file when repoting an issue)
https://www.dropbox.com/s/z81f2j7d29zus3q/LoaderErrs.txt?dl=0

Scott

**Comment by scottb5612** [comment]
These errors don't occur when I build redty3.

**Comment by SergioMartin86** [comment]
You'll have to let me know what command you are using for linking

**Comment by scottb5612** [comment]
I set up a care package for you , it's here

https://www.dropbox.com/sh/buuz18kevnyfil9/AABKKRWT1oGyeWWRijuDhMg1a?dl=0

make.sh contains the commands I used

If you run at NYU, be sure to look at the BASHRC file for how to set up the environment
(I now use  the MPI wrappers)

THe Makefile and an include file of variables is there as well ( MakefileVars.X86_64_ICC)

Here are the commands I used to translate and compile superMain.c

bamboo-translate superMain.c -fpermissive -I./include -I/home/sbaden/cart3d/include -I/home/sbaden/include -I/usr/include/libxml2

bamboo-cxx -c -fpermissive -I./include -I/home/sbaden/cart3d/include -I/home/sbaden/include -I/usr/include/libxml2 bamboo_superMain.cpp

Note that Allgatherv is called only once (from GenAdjMat() in genRecvLists_no_mpi.c), yet there are  multiple invocations (10)  of Bamboo_Allgatherv the generated code  GenAdjMat is called by various 
"Get" routines (GetRecvList() and various GetRecvListXXXX()), from code that contains overlap regions. So when each  of the Get routines gets inlined up to main, that means that Allgatherv gets inlined.

**Comment by scottb5612** [comment]
There seems to be 2 different types of loader problems.

1. One is   an internal method in Bamboo, getsizeof()
In function `OlapClass79::executeOlapRegion79()':
bamboo_superMain.cpp:(.text._ZN11OlapClass7919executeOlapRegion79Ev[_ZN11OlapClass7919executeOlapRegion79Ev]+0x11f): undefined reference to `getsizeof(int)'

2. Another is to some entries in libstdc++, such as
std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)

I think you have some digging around to do to solve #1.
I think I see what may be happening with #2.
I need to use the loader that was used to build bamboo/tarragon.
Otherwise I'll get the wrong libstdc++

Ok, it's late now.
I will mull this over.

**Comment by SergioMartin86** [comment]
I cannot test it yet, but the getsizeof problem should be solved now.

**Comment by scottb5612** [comment]
Yes, it is.  Thank you.
