### ISSUE TITLE
Perform cleanup at Post-Processing stage

### ISSUE THREAD

**Issue by SergioMartin86** [SergioMartin86/bamboo6#39]
- Remove Bamboo Pragmas
- Remove comments ?
What else?

**Comment by scottb5612** [comment]
Sergio, based on my experience with Bamboo, I've found the
comments particularly useful when debugging, and the pragmas useful at time as well.
The comments are sometimes needed to  find one's place in the bamboo generated code, that
is, what input code certain lines correspond to. Though code does get reordered I have often use the comments as "bread crumbs" to help figure out where I am. Bamboo code can be very hard to read as it is, those comments help. I suggest you maintain the pragmas but as some kind of comment . The pragmas can also help identify ones place in the code, as with the comments.

**Comment by SergioMartin86** [comment]
That's fine, I see the point in leaving the comments and pragmas there.
