### ISSUE TITLE
Multi-file compilation

### ISSUE THREAD

**Issue by SergioMartin86** [SergioMartin86/bamboo6#41]
Scott: Can you try compiling cart3d with multiple files again? I think the problem you had might be solved.

If its not, let's follow it up until it works.

**Comment by scottb5612** [comment]
After removing the dimension pragma, I was unable to translate the code
anywhere (at NYU   on Sorken and on Stampede)
I've saw this error the other day
It would be good to have a version number printed out via a -v comand

## At NYU
sbaden@**juniper**[mpix_flowCart]$ bcxx bamboo_main.cpp 
bamboo_main.cpp:762:1: error: unterminated #else
bamboo_main.cpp: In member function ‘virtual void _BambooTask::vexecute()’:
bamboo_main.cpp:8024: error: ‘limitGradients’ was not declared in this scope

## On Sorken
[baden@**sorken** mpix_flowCart]$ bcxx bamboo_main.cpp 
bamboo_main.cpp:762:0: error: unterminated #else
bamboo_main.cpp: In member function ‘virtual void _BambooTask::vexecute()’:
bamboo_main.cpp:8013:88: error: ‘limitGradients’ was not declared in this scope

## On Stampede

login3.**stampede**$ bcxx bamboo_main.cpp 
bamboo_main.cpp:762:0: error: unterminated #else
bamboo_main.cpp: In member function ‘virtual void _BambooTask::vexecute()’:
bamboo_main.cpp:8024:88: error: ‘limitGradients’ was not declared in this scope

**Comment by scottb5612** [comment]
I rebuilt bamboo at NYU.
I cannot build bamboo if I use gcc 4.7.2 and the Intel front end compilers.
I'm OK with gcc 4.4.7, that is, I can translate cart3d but not compile (as above)
But I still cannot build 7-point whereas I can build it on sorken and stampede.
For me, it's cart3d that's crucial, so will wait until the above error  is solved.

**Comment by SergioMartin86** [comment]
you didn't use coan to remove the #ifdef #else #endif directives, right?

**Comment by scottb5612** [comment]
That is the whole point of using coan.
Bamboo v5.4 could not handle conditionally compiled code.

**Comment by SergioMartin86** [comment]
Well, this is interesting and I really wanna talk about it with the ROSE team. 

This is something the EDG frontend should be doing,  or at least representing in the AST. In both cases, there is a possibility to do something about these directives. In case it just ignores them, then yes, there's nothing we can do from Bamboo.

Alternative 1 would be to integrate (automatically download and install) coan into Bamboo's dependencies. But we would have to check if Coan's license allows this. If not:

Alternative 2, advise users in the user's manual to handle these directives manually or with coan.

**Comment by scottb5612** [comment]
Let me know what you find out.
In the meantime, let's use superMain approach.
I need to start debugging code and there will likely be more surprises.

Are there any outstanding issues with the current version of bamboo
if I use just superMain?

**Comment by SergioMartin86** [comment]
None at all, superMain should be fine. In fact, I'm being able to compile it fine.

Today I'll start setting up my linking/executing environment for cart3d as per the instructions you sent me. I may need some guidance at some point though.

**Comment by scottb5612** [comment]
I made some changes to various code modules.
At this point, I would re-copy everything you have
Scott

**Comment by scottb5612** [comment]
PS Incorporating coan is a reasonable strategy, hopefully we aren't prevented from  doing so.
After all, Rose uses tools like Boost.

**Comment by SergioMartin86** [comment]
I've read the license file in Coan and it allows redistribution and all, given the license is included. So this is good to go.

I would like, however, to see if ROSE or EDG provide this functionality, because using coan would mean some file manipulation that I would really love to avoid.

**Comment by SergioMartin86** [comment]
I have good and bad news...

Bad news: Coan won't be enough for what we need.
Good news: I've found an even better solution.

Can we talk sometime soon so I can explain the situation? Also I need to explain what I did with the layout and dimension parameters.

**Comment by SergioMartin86** [comment]
Uuuughhhhh it was so eaaaaaaasy in the end.... you won't believe how I got this fixed.

**Comment by SergioMartin86** [comment]
Ok, I've been able to successfully translate and compile cart3d with these commands:

> bamboo-translate main.c mpi_par.c mpi_par_types.c mpi_par_bcast.c mpi_par_snd_rcv.c mpi_par_exchange.c mpi_exchange_promgstuf.c mpi_exchangeGradient.c mpi_exchange_resmgstuff.c genRecvLists.c mesh_io_fill_partitionsSFC.c setup.c mesh_io_mpi.c limiters.c do_mg_cycle.c mg_stuff.c runge_kutta.c convergence.c -DLINUX64 -DNO_ALLOCA -DSTICKLER -DUNROLL_MG=1 -D_BAMBOO_ -I./include -I../cart3d/include -I../include -I/usr/include/libxml2
> bamboo-cxx bamboo_main.cpp -I./include -I../cart3d/include -I../include -I/usr/include/libxml2

I had to add "void limitGradients(p_tsGrid p_g, const limtype, const int level, gstore *glbls);" at the top of main.c because that function is defined in runge_kutta.c and needs to be declared. (Ideally, all functions should be declared in their corresponding .h files).

Let me know how it went for you and reopen if fails.

Next step for me is linking...

**Comment by scottb5612** [comment]
Do you mean that in the end coan did the job and you didn't need somthing else?
Do you still wan to talk?

**Comment by scottb5612** [comment]
Functions are  generally be declared in include/prototypes.h, except for local functions in code translated by bamboo.  This ensures that code will get declared superMain.
I can see that I didn't put the definition for limitGradients inside prototype.h, which I did for
a number of other functions last fall. as I was porting Marsha's original code to Bamboo. You can see the comment about a local prototype (in runge_kutta.c. That's not correct any more.

So I moved the routine into prototypes.h
Let me know if that works for you.
We should be doing things systematically
Scott

**Comment by SergioMartin86** [comment]
I just see this message. Yes, as I put in the other issue, we need to have a way to coordinate our modifications to cart3d.

About Coan... it is just not the right tool because it is incapable of iterating over #include files. This is a deal breaker because many of the definitions used in #ifdef come from .h files. Even Tarragon is plagued with them.

No, the truth is much funnier than than. We were chasing our own tails really. There was never a problem to start with. When I tell you over the phone what the issue was, you'll see why!

**Comment by scottb5612** [comment]
What do you mean by iterating over include file?

**Comment by SergioMartin86** [comment]
for example, if you have:

#include "definitions.h"
int main()
{
   #ifdef SOME_DEF
      printf("It's defined");
   #else
     printf("It's NOT defined");
   #endif
}

If you don't pass any parameters to coan, it won't be able to decide if SOME_DEF is defined or not (if you use -m, it will assume SOME_DEF is not defined). However, definitions.h may hold information about SOME_DEF. Bad thing is coan does not resolve header files, and doesn't read definitions.h. 

Unfortunately, the vast majority of defines are placed in header files, instead of being passed as -D arguments to the compiler preprocessor. This kinda renders coan non-viable for use with an automatic tool such as Bamboo. Coan is more useful for developers to simplify legacy code and stuff.
