### ISSUE TITLE
Bamboo doesn't inline MPI functions if they are more than 1 step away

### ISSUE THREAD

**Issue by SergioMartin86** [SergioMartin86/bamboo6#43]
This is because Bamboo inlines only if immediate next function has MPI, but not if the function doesn't have any MPI calls (even if it has calls to functions with MPI).

This affects cart3d because limitGradients doesn't have MPI and doesn't get inlined, but does call to mpi_exchangeGradient which has MPI.

**Comment by SergioMartin86** [comment]
My bad, this is not a bamboo malfunction. This is because, for some reason ROSE is not being able to find limitGradients definition. I'm looking into this.

**Comment by scottb5612** [comment]
That doesn't make sense.
Bamboo should inline clear up to main, back up through the complete call chain, starting
from the MPI. I think you are saying that this is not the case. Could you clarify?

limitGradients -> mpi_exchangeGradient -> Calls to MPI

**Comment by scottb5612** [comment]
Didn't you see my post about putting limitGradients into include/prototyeps.h?

**Comment by SergioMartin86** [comment]
Yes, I saw it. I realized that it wasn't a problem of Bamboo, but a shared problem of ROSE and the way limitGradients is programmed. 

Check https://github.com/SergioMartin86/bamboo6/issues/44 for my thoughts on that.
