### ISSUE TITLE
treatment of command line arguments

### ISSUE THREAD

**Issue by scottb5612** [SergioMartin86/bamboo6#5]
At present, the argument vector, conventionally known
as  "argv"  must be named argv.
However, this is not a restriction of C/C++, for example,
the following should be accepted

int main(int argc, char* p_argv[])

**Comment by SergioMartin86** [comment]
This has been solved in the last revision.

**Comment by scottb5612** [comment]
I see that you changed the name of the argument list in the 7 point exaple
to test.
Good.
Scott
