### ISSUE TITLE
7 point solver hangs

### ISSUE THREAD

**Issue by scottb5612** [SergioMartin86/bamboo6#6]
I cleaned up the 7 point solver example a little bit, you can find it here.
It has improved error checking and outputs some useful information
I tried to add a true   non-homogenous right hand side, but couldn't get it to work correctly, unless I set it to zero as in the original codeThis requires more thought.

But the bigger problem is that although bamboo translates the code without incident,
bamboo-cxx fails

The code is here, use it instead of what's in the example directory

https://www.dropbox.com/s/yxw6uot6r3qipmx/7_point_stencil.cpp?dl=0

**Comment by SergioMartin86** [comment]
I was aware of this problem and solved it this morning. It was not a problem with the codefile but with the run script. Basically, it was missing the dimension size arguments.

It should work now, both the original and Bamboo versions.

I'll proceed now to implement the changes you made to the original one, and close this bug when that's done.

**Comment by SergioMartin86** [comment]
This should be solved now. I recommend proceeding with an almost clean install:
- Update your local repo
- Delete everything in install dir except for rose and boost
- make clean install
