### ISSUE TITLE
bamboo's log file

### ISSUE THREAD

**Issue by scottb5612** [SergioMartin86/bamboo6#7]
It would be nice if the log file were named using the same convention as 
bamboo's output. Currently the file is just called bamboo.log.

Thus, if I translate different files in the same directory, the log files will continually overwrite one another.

7_point_stencil.cpp generates
bamboo_7_point_stencil.cpp

I suggest
bamboo_7_point_stencil.log
rather than bamboo.log

**Comment by SergioMartin86** [comment]
This has been implemented. Also suppressed EDG frontend warning messages for a smalled logfile.
