### ISSUE TITLE
Important bamboo warnings

### ISSUE THREAD

**Issue by scottb5612** [SergioMartin86/bamboo6#8]
Bamboo reports some important information in the log file

[Bamboo] Warning: Found stray statement outside compute block.

This should be reported to the terminal, too, and   as an error
 ather than as a warning.  

Recall that bamboo requires that any code appearing within an overlap region
must be properly enclosed in a send or a receive block
Other code must be enclosed within a compute block 
(but only 1 compute block may appear with an overlap region)
So what I think  the above  message is saying is that it found
code not enclosed within a send/recv/compute block, appearing within an olap region.

Probably best not to assume the intent of the coder; the extraneous
code may have been truly extraneous (i.e. to be removed), or the coder meant
to put it  in a send or receive block rather than a compute block 
So the message should probably say something like

"found code within an olap region not properly enclosed within a send/receive/compute block"

It would really help to output the offending code and the line number(s)
to help track down the problem.

This error message appeared in the example code I sent you.
I found the offending code (actually 2 lines, not 1 line as reported in the warning message)
It's within an "if"" statement that printouts out the iteration number
Scott

**Comment by SergioMartin86** [comment]
[Bamboo] Warning: Found stray statement outside compute block.

Is a warning I added to remind myself to integrate bamboo checker into bamboo (not as an external tool). I am removing this warning now and adding an enhancement issue.
