### ISSUE TITLE
Annotating olap regions

### ISSUE THREAD

**Issue by scottb5612** [SergioMartin86/bamboo6#9]
I think you told me that you fixed the need to enclose
an olap region within { }

So this is legal now

#pragma bamboo olap 
for (...)
{
}

and it's not necessary to add the enclosing {} 

#pragma bamboo olap 
{
for (...)
{
}
}

But I think it may be necessary, or, I can explain the warning messages I'm getting
about stray statements outside compute block. When I add those extra curly braces,
the number of warning messages is reduced. It was just a hunch.
Trouble is, I cannot eliminate al those stray warnings, there are still 14 left (7 point example)

**Comment by scottb5612** [comment]
I think the collectives may be causing these error messages to appear
When I commented out the MPI_Reduce statement in the 7-point example,
the # of warning messages was reduced-- though not to 0! (It's 10)

Removing the barrier has no effect.

**Comment by SergioMartin86** [comment]
[Bamboo] Warning: Found stray statement outside compute block.

Is a warning I added to remind myself to integrate bamboo checker into bamboo (not as an external tool). I am removing this warning now and adding an enhancement issue.
